language: groovy
sudo: false
jdk:
  - openjdk7
sudo: false
branches:
  only:
  - master
  - 2015-design
  - may2017redesign
cache:
  directories:
    - ~/.m2/repository
    - ~/.grails/wrapper
before_install:
- wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
- chmod +x ala_common.sh
- source ./ala_common.sh
- ala_travis_grails_repo_setup

script:
- ala_travis_grails_build

env:
  global:
  - secure: Yi3Kl8E+fDy+PLzfiLZkS5UdQ969ymKNbwzymL1TU93ZhHY2BbBigJpalYp9ZzHTmzCTdIqsrSHxlclTegAtCsm4zGjihgO7YGrCi0NXDfP7P2pmTqGb1XNJx2WnkZ+9sNISRarYg5LvtPON2Ae6Gk5vTYJmRFCvnS2/QoPM15Q=
  - secure: O879SzvwfrfdR6KCywiGUbvTieGktQU834FVm8KDoThjF8+HgDFk0TFBNLip/yDtpYDfmYtAbXI0nYkzuPC0s0CTjA3oSexMIs2MU84qib7RZLa3KTwvLPqndb4UbdkDcpjFYojsIio9r8H0bsVh2VmGKsq5oWpdudlMnwfmLqU=
